<?php
require 'vendor/autoload.php';
use Dompdf\Dompdf;

// Check if file is uploaded
if(isset($_FILES['fileToUpload'])) {
    $errors = array();
    $file_name = $_FILES['fileToUpload']['name'];
    $file_size = $_FILES['fileToUpload']['size'];
    $file_tmp = $_FILES['fileToUpload']['tmp_name'];
    $file_type = $_FILES['fileToUpload']['type'];
    $file_parts = explode('.', $_FILES['fileToUpload']['name']);
    $file_ext = strtolower(end($file_parts));

    $extensions = array("html","htm");

    if(in_array($file_ext,$extensions) === false){
        $errors[] = "extension not allowed, please choose a HTML file.";
    }

    if(empty($errors) == true) {
        // Read the file content
        $htmlContent = file_get_contents($file_tmp);

        // instantiate and use the dompdf class
        $dompdf = new Dompdf();

        // Load HTML content
        $dompdf->loadHtml($htmlContent);

        // (Optional) Setup the paper size and orientation
        $dompdf->setPaper('A4', 'landscape');

        // Render the HTML as PDF
        $dompdf->render();

        // !!! Necessary to turn off error reporting with dompdf due to the warning generated by Dompdf
        error_reporting(0);

        // Output the generated PDF to Browser, but don't allow file download directly
        $dompdf->stream("", array("Attachment" => false));

        // Turn error reporting back on
        error_reporting(E_ALL);
    } else {
        print_r($errors);
    }
} else {
    // Display the upload form if no file is uploaded
    echo '
    <form action="" method="post" enctype="multipart/form-data">
        Избери HTML файл за качване(Dompdf):
        <input type="file" name="fileToUpload" id="fileToUpload">
        <input type="submit" value="Конвертирай" name="submit">
    </form>
    ';
}
?>